spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://ink-book.mysql.cn-chengdu.rds.aliyuncs.com:3306/ink_book
      username: ink_book
      password: Ink_book

  mail:
    host: smtp.qq.com
    default-encoding: UTF-8
    username: ink_book@qq.com
    password: kulqdeonfsuuchej
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml